jwt:
  api:
    alg: HS256
    key: "shared99secret!"
    aud: https://api.myome.info/
    iss: "me"
    lifetime: 604800  # 7 days

  auth0:
    alg: RS256
    aud: https://api.myome.info/

    # public key extract from cert with
    # openssl x509 -pubkey -in cert.pem 
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArkPSTIE+t13R5+RJ2Eql
      YqKL4AuN7ysvzsOmRr2wjqfcQiYNrjDEmoZ2SIOBRrJoKr37ARC1Ok8pFx2nKt4n
      FCIny/BLt/H4HrloSgptCQhTNpm0TVD4JFP1vX7f0zxROz3uzVSCXRqA3Mhfgwmd
      T+2wwY4833u2+rEAe/i1TmvFDz3245/IcfYuh+u48+3RXp3gu0Tkj2ifaeXhjaJ4
      ckXn/V1iJeSCFFWfaj437kg2Gbgk16NDfU7e0AAiuHpWDHu4M74eOlI2D08rkukf
      3MhTu1JjBSfkoFZ6rbHBXZjA05ocgODPPG5p0McL0056tMADIAAiqkQEmviwonSC
      HwIDAQAB
      -----END PUBLIC KEY-----

